const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const root=document.querySelector('#root');
let tab='world', claimed=false, started=false, notice=true;
const icon=(x)=>`<span class="glyph" aria-hidden="true">${x}</span>`;

function top(){return `<header class="topbar"><div class="profile"><div class="avatar main">A</div><div><small>ИССЛЕДОВАТЕЛЬ</small><b>Alex</b></div></div><div class="resources"><div class="resource"><span class="credit">◉</span><b>240</b></div><div class="resource"><span class="energy">ϟ</span><b>18</b></div><div class="resource"><span class="crystal">◆</span><b>3</b></div></div><button class="bell" data-action="notice" aria-label="Уведомления">♢${notice?'<i/>':''}</button></header>`}
function creature(){return `<div class="creature" aria-label="Эйко, ваш спутник"><div class="ear left"></div><div class="ear right"></div><div class="body"><div class="mark">✦</div><i class="eye e1"></i><i class="eye e2"></i><div class="mouth">⌣</div></div><div class="tail"></div></div>`}
function world(){return `<section class="hero"><div class="sky"><span class="planet p1"></span><span class="planet p2"></span><span class="star s1">✦</span><span class="star s2">·</span></div><div class="land back"></div><div class="land mid"></div><div class="world-home"><span class="roof"></span><span class="hut"><i></i></span></div><div class="trees">♠ ♠ ♠</div>${creature()}<div class="world-label"><small>ВАШ МИР</small><strong>Люмен-7</strong><span><i></i> Рассвет · День 1</span></div></section>
<section class="return-card"><div class="return-icon">⌁</div><div><small>ПОКА ТЕБЯ НЕ БЫЛО…</small><p>Эйко нашёл светящееся семя у ручья.</p></div><button data-action="claim" class="${claimed?'claimed':''}">${claimed?'Получено':'Забрать'}<span>+12</span></button></section>
<section class="section-head"><div><small>ПЕРВЫЕ ШАГИ</small><h2>${claimed?'Мир услышал тебя':'Пробуди свой мир'}</h2></div><span class="progress">2 / 4</span></section>
<div class="quest-card"><div class="quest-art"><span class="compass-ring">⌖</span></div><div class="quest-copy"><span>СЛЕДУЮЩИЙ ШАГ</span><h3>Первая экспедиция</h3><p>Исследуй туманный лес вместе с Эйко.</p><div class="reward"><b>НАГРАДА</b><span>◉ 80</span><span>✦ 5</span></div></div><button class="go" data-tab="explore" aria-label="К экспедиции">›</button></div>
<section class="section-head"><div><small>ПОСЕЛЕНИЕ</small><h2>Тихая поляна</h2></div><button class="text-btn">Все здания ›</button></section><div class="buildings">${[['⌂','Дом Эха','Ур. 1'],['♧','Сад энергии','Готово через 4м'],['▣','Мастерская','Откроется завтра']].map((b,i)=>`<article class="${i===2?'locked':''}"><div class="building-icon b${i}">${b[0]}</div><div><h3>${b[1]}</h3><p>${b[2]}</p></div>${i===1?'<span class="ready">ГОТОВО</span>':''}</article>`).join('')}</div>`}
function explore(){return `<main class="page padded"><header class="page-title"><small>КАРТА БИОМОВ</small><h1>За горизонтом</h1><p>Каждый выбор меняет Эйко и историю мира.</p></header><div class="map-card"><span class="node home-node">⌂</span><span class="path"></span><span class="node forest-node">♠</span><span class="locked-node">▣</span><div class="map-caption"><b>Туманный лес</b><span>Первая экспедиция · 2 мин</span></div></div><div class="choice"><span class="eyebrow">ЭКСПЕДИЦИЯ 01</span><h2>${started?'Эйко отправился в путь':'Шёпот среди деревьев'}</h2><p>${started?'Вернись через две минуты. Твоя осторожность уже стала частью его характера.':'В чаще мерцает незнакомый свет. Запасов хватит на один маршрут.'}</p>${started?'<div class="timer">01:58 <small>Можно закрыть приложение</small></div>':'<button class="primary" data-action="start">⌖ Исследовать бережно <span>ϟ 5</span></button><button class="secondary">Пойти напрямик</button>'}</div></main>`}
function social(){return `<main class="page padded"><header class="page-title"><small>СОЦИАЛЬНАЯ КАРТА</small><h1>Соседние миры</h1><p>Оставляй след — не забирая чужое.</p></header><div class="echo-banner">${icon('◇')}<div><small>PLAYER ECHO</small><h2>Подари часть своей истории</h2><p>Оставленный объект навсегда сохранит имя твоего мира.</p></div></div>${['@mira · Астэр','@lev · Ковчег-3','@nox · Северный свет'].map((x,i)=>`<article class="friend"><div class="avatar a${i}">${x[1].toUpperCase()}</div><div><h3>${x}</h3><p>${i?'Был недавно':'Нужна помощь в саду'}</p></div><button>${i?'В гости':'Помочь'}</button></article>`).join('')}<button class="invite">♧ Пригласить друга <span>+50 ◉</span></button></main>`}
function nav(){return `<nav><button class="${tab==='world'?'active':''}" data-tab="world">${icon('⌂')}<span>Мир</span></button><button class="center ${tab==='explore'?'active':''}" data-tab="explore"><span>⌖</span><b>Исследовать</b></button><button class="${tab==='social'?'active':''}" data-tab="social">${icon('♧')}<span>Связи</span></button></nav>`}
function render(){root.innerHTML=`<div class="app">${top()}<div class="content">${tab==='world'?world():tab==='explore'?explore():social()}</div>${nav()}</div>`}
root.addEventListener('click',e=>{const target=e.target.closest('[data-tab],[data-action]');if(!target)return;if(target.dataset.tab){tab=target.dataset.tab;tg?.HapticFeedback?.impactOccurred('light')}if(target.dataset.action==='claim')claimed=true;if(target.dataset.action==='start')started=true;if(target.dataset.action==='notice')notice=false;render()});
render();
